require("sironheart-nvim.plugins.basic")
require("sironheart-nvim.plugins.completion")
require("sironheart-nvim.plugins.git")
require("sironheart-nvim.plugins.harpoon")
require("sironheart-nvim.plugins.lsp")
require("sironheart-nvim.plugins.neo-tree")
require("sironheart-nvim.plugins.telescope")
require("sironheart-nvim.plugins.which-key")
